[package]
name = "cosmos"
version = "0.1.0"
authors = ["zc <zhichuan.liang@shopee.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
